version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:21.0.2

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
            name: Install APT dependencies
            command: |
              sudo apt update
              sudo apt install -y findutils
      - run:
          name: Build server application
          command: |
            mkdir -p build/libs
            javac -cp 'libs/linux/*' -d build/classes $(find src -name '*.java')
            jar --create --file build/libs/MinecraftServer.jar --manifest <(echo "Main-Class: fr.math.minecraft.ServerMain") -C build/classes .
            jar --update --file build/libs/MinecraftServer.jar -C libs/linux .

  deploy:
    executor: docker-executor
    steps:
      - run:
          name: Install SSH Client
          command: |
            sudo apt-get update && sudo apt-get install -y openssh-client
      - run:
          name: Add VPS host to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -p $PORT -H $HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy application
          command: |
            ssh $USERNAME@$HOST -p $PORT 'cd /opt/Minecraft_Clone sh /opt/Minecraft_Clone/deploy.sh'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build